version: '3'

services:
  backend:
    container_name: backend_container
    build: 
      context: .
      dockerfile: apps/docker/backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  frontend:
    container_name: frontend_container
    build: 
      context: .
      dockerfile: apps/docker/frontend/Dockerfile
    ports:
      - "80:80"
    volumes:
      - node_modules:/apps/frontend/node_modules
    env_file:
      - ./.env

  nginx:
    container_name: nginx_container
    build: 
      context: .
      dockerfile: apps/docker/nginx/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - static:/apps/backend/static

    depends_on:
      - backend
      - frontend

volumes:
  db-data:
  node_modules:
  static: