# Generated by Django 5.0.1 on 2024-01-15 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_category_categoryentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyTypeEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='productentity',
            name='category',
        ),
        migrations.RenameField(
            model_name='userentity',
            old_name='user',
            new_name='username',
        ),
        migrations.AddField(
            model_name='keyentity',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='keyentity',
            name='expired',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='keyentity',
            name='key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterModelTable(
            name='keyentity',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userentity',
            table=None,
        ),
        migrations.AlterField(
            model_name='keyentity',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.keytypeentity'),
        ),
        migrations.DeleteModel(
            name='CategoryEntity',
        ),
        migrations.DeleteModel(
            name='ProductEntity',
        ),
        migrations.DeleteModel(
            name='TypeKeyEntity',
        ),
    ]
